CREATE TABLE gacha (
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 16),
    uuid             VARCHAR NOT NULL,
    name             VARCHAR NOT NULL,
    description      VARCHAR,
    image_path       VARCHAR,
    rarity_id        INTEGER NOT NULL,

    UNIQUE(uuid),
    UNIQUE(name)
);

CREATE TABLE rarity (
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 6),
    name             VARCHAR,
    symbol           VARCHAR,

    UNIQUE(name)
);

INSERT INTO rarity (id, name, symbol) VALUES 
    (1, 'Common',    'C'), 
    (2, 'Uncommon',  'U'), 
    (3, 'Rare',      'R'), 
    (4, 'Epic',      'E'), 
    (5, 'Legendary', 'S');

INSERT INTO gacha (id, uuid, name, description, image_path, rarity_id) VALUES
    (1,  '4e120c8c-d5c0-43f6-8587-0a8b94473593', 'Orc',           'placeholder', '/assets/images/gachas/Orc (common).jpg',         1),
    (2,  '09907f76-9b0f-4270-84a3-e9780b164ac4', 'Goblin',        'placeholder', '/assets/images/gachas/Goblin (common).jpg',      1),
    (3,  '8930305e-262f-4ae9-92a0-f6d5dccc4d1f', 'Skeleton Mage', 'placeholder', '/assets/images/gachas/Skeleton (common).jpg',    1),
    (4,  'dde21dde-5513-46d2-8d03-686fc620394c', 'Undead',        'placeholder', '/assets/images/gachas/Undead (non-common).jpg',  2),
    (5,  '0b75b774-9783-4bdc-b54a-4b8e9806399e', 'Cyclops',       'placeholder', '/assets/images/gachas/Cyclops (non-common).jpg', 2),
    (6,  'cd6d4ae7-27a3-43cc-a2e5-b067f77c0744', 'Harpy',         'placeholder', '/assets/images/gachas/Harpy (non-common).jpg',   2),
    (7,  'c6cc4f1f-f5f8-4e76-a446-b01b48b10575', 'Demon',         'placeholder', '/assets/images/gachas/Demon (rare).jpg',         3),
    (8,  'd00d0e34-0250-4c21-b4f8-12109f3925b0', 'Cerberus',      'placeholder', '/assets/images/gachas/Cerberus (rare).jpg',      3),
    (9,  '6150d92e-3592-46e2-8184-b3b5f2a8b684', 'Skeleton',      'placeholder', '/assets/images/gachas/Skeleton (rare).jpg',      3),
    (10, 'a3bc71a1-44e9-4ac5-8215-c30666720ec5', 'Dragon',        'placeholder', '/assets/images/gachas/Dragon (rare).jpg',        4),
    (11, '6cc1d008-d047-4147-ba6f-25cba2bdf061', 'Minotaur',      'placeholder', '/assets/images/gachas/Minotaur (epic).jpg',      4),
    (12, 'a954690a-5be4-443b-9137-92c73bee5480', 'Vampire',       'placeholder', '/assets/images/gachas/Vampire (epic).jpg',       4),
    (13, '7d1fec59-6a89-4b78-a9e5-aa4d0d10478e', 'Phoenix',       'placeholder', '/assets/images/gachas/Phoenix (legendary).jpg',  5),
    (14, '3b8009f2-31c8-484b-aa74-32defbb02985', 'Kraken',        'placeholder', '/assets/images/gachas/Kraken (legendary).jpg',   5),
    (15, '23255124-b509-41fd-b607-5f5da9f60447', 'Griffin',       'placeholder', '/assets/images/gachas/Griffin (legendary).jpg',  5);

SELECT setval('rarity_id_seq', (SELECT max(id) FROM rarity));
SELECT setval('gacha_id_seq', (SELECT max(id) FROM gacha));