CREATE TABLE auction (
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uuid             VARCHAR NOT NULL,
    base_price       INTEGER NOT NULL,
    expired_at       BIGINT NOT NULL,

    UNIQUE(uuid)
);
 
INSERT INTO auction (id, uuid, base_price, expired_at) VALUES 
    (1, '71520f05-80c5-4cb1-b05a-a9642f9ae44d', 200, 143011112024);