CREATE TABLE player (
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uuid             VARCHAR NOT NULL,
    username         VARCHAR NOT NULL,
    password_hash    VARCHAR NOT NULL,
    wallet           INTEGER NOT NULL DEFAULT 0,

    UNIQUE(uuid),
    UNIQUE(username)
);

INSERT INTO player (id, uuid, username, password_hash, wallet) VALUES 
    (1, '71520f05-80c5-4cb1-b05a-a9642f9ae44d', 'test', '$2b$12$Z93LSBi0EVtyqVWnZB7tPu8ksgXbrFPd8YjI1haMzGl7KBLrbaR6G', 100); -- psw: test

SELECT setval('player_id_seq', (SELECT max(id) FROM player));