openapi: 3.0.0
info:
  title: Currency Service API
  version: 1.0.0
  description: API to manage currency functionalities for the application

servers:
  - url: https://127.0.0.1:8088
    description: Currency API

tags:
  - name: Currency
    description: Operations related to currency functionality

paths:
  /currency/buy:
   put:
     summary:  Purchasing in game Currency
     operationId: buy
     tags:
       - Currency
     requestBody:
      content:
           application/json:
             schema:
               type: object
               properties:
                 purchase:
                   type: number
     responses:
       '200':
         description: Purchased Successful
         content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              example:
                response: "wallet updated Successfully!"
       '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                no_currency:
                  value:
                    response: "Invalid purchase"
       '401':
         description: Unauthorized
         content:
           application/json:
             schema:
               type: object
               properties:
                 response:
                   type: string
             examples:
               not_logged:
                 value:
                   response: "You are not logged"
       '403':
           description: Forbidden
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   response:
                     type: string
               examples:
                 invalid_token:
                   value:
                     response: "Invalid Token"
                 expired_token:
                   value:
                     response: "Expired Token"