openapi: 3.0.0
info:
  title: EzGacha
  version: 1.0.0
  description: API to manage accounts, collections, currencies, and market functionalities for a players and admins

servers:
  - url: https://localhost:8080
    description: Player API

tags:
  - name: Player
    description: Operations related to Player DB manager

paths:
  /:
    get:
      summary: Get all players list
      operationId: show_all
      tags:
        - Player
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: array
                    items:
                      $ref: "#/components/schemas/UserProfile"

  /uuid/{player_uuid}:
    get:
      summary: Show players list
      operationId: show_by_uuid
      tags:
        - Player
      parameters:
        - name: player_uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: transaction uuid is not correct
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/UserProfile"
        "400":
          description: transaction uuid is not correct
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                incorrect_uuid:
                  value:
                    response: "Error: player not found"
    put:
      summary: Modify player account
      tags:
        - Player
      requestBody:
        description: Account details for creation
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                wallet:
                  type: number
      responses:
        "200":
          description: Player modification
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              example:
                response: "User updated Successfully!"

        "400":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                not_found:
                  value:
                    response: "Error: player not found"
                invalid_wallet:
                  value:
                    response: "Invalid wallet"

components:
  schemas:
    UserProfile:
      type: object
      description: Player of the game
      properties:
        uuid:
          type: string
          description: Unique identifier of the User
        username:
          type: string
          description: Unique nickname of the User
        wallet:
          type: number
          description: In game currency of the User (default 0)
