CREATE TABLE admin (
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username           VARCHAR NOT NULL,
    password_hash      VARCHAR NOT NULL,

    UNIQUE(username)
);

INSERT INTO admin (id, username, password_hash) VALUES
    (1, 'admin', '$2b$12$QnbxGRl6jVTzt.fbksJWVuITmX4832AnfF1uSx00hZSsDBgjXDxcO'); -- psw: admin

SELECT setval('admin_id_seq', (SELECT max(id) FROM admin));