services:
  player_db:
    build: ./dbs/player
    container_name: player_db
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
     - path: ./dbs/player/.env

  authentication_db:
    build: ./dbs/authentication
    container_name: authentication_db
    ports:
      - "127.0.0.1:5433:5432"
    env_file:
      - path: ./dbs/authentication/.env

  gacha_db:
    build: ./dbs/gacha/
    container_name: gacha_db
    ports:
      - "127.0.0.1:5434:5432"
    env_file:
     - path: ./dbs/gacha/.env

  account_db:
    build: ./dbs/account/
    container_name: account_db
    ports:
      - "127.0.0.1:5435:5432"
    env_file:
     - path: ./dbs/account/.env

 
  player_service:
    build: ./services/player
    container_name: player_service
    env_file:
      - path: ./services/player/.env
    ports:
      - "127.0.0.1:8080:5000"
    depends_on:
      - player_db
    links:
      - player_db
    develop:
     watch:
      - action: sync
        path: ./services/player/src
        target: /app
      - action: rebuild
        path: ./services/player/requirements.txt

  authentication_service:
    build: ./services/authentication
    container_name: authentication_service
    env_file:
      - path: ./services/authentication/.env
    ports:
      - "127.0.0.1:8081:5000"
    depends_on:
      - authentication_db
    links:
      - authentication_db
    develop:
     watch:
      - action: sync
        path: ./services/authentication/src
        target: /app
      - action: rebuild
        path: ./services/authentication/requirements.txt

  gacha_service:
    build: ./services/gacha
    container_name: gacha_service
    env_file:
      - path: ./services/gacha/.env
    ports:
      - "127.0.0.1:8082:5000"
    depends_on:
      - gacha_db
    links:
      - gacha_db
    develop:
     watch:
      - action: sync
        path: ./services/gacha/src
        target: /app
      - action: rebuild
        path: ./services/gacha/requirements.txt

  account_service:
    build: ./services/account
    container_name: account_service
    env_file:
      - path: ./services/account/.env
    ports:
      - "127.0.0.1:8083:5000"
    depends_on:
      - account_db
    links:
      - account_db
    develop:
     watch:
      - action: sync
        path: ./services/account/src
        target: /app
      - action: rebuild
        path: ./services/account/requirements.txt
    




