services:
  caddy:
    image: caddy:latest
    container_name: caddy_gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - player_service
      - authentication_service
      - gacha_service
      - account_service
      - currency_service
      - market_service
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config

  player_db:
    build: ./dbs/player
    container_name: player_db
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
     - path: ./dbs/player/.env
    volumes:
     - player_db:/var/lib/postgresql/data

  authentication_db:
    build: ./dbs/authentication
    container_name: authentication_db
    ports:
      - "127.0.0.1:5433:5432"
    env_file:
      - path: ./dbs/authentication/.env
    volumes:
     - authentication_db:/var/lib/postgresql/data

  gacha_db:
    build: ./dbs/gacha/
    container_name: gacha_db
    ports:
      - "127.0.0.1:5434:5432"
    env_file:
     - path: ./dbs/gacha/.env
    volumes:
     - gacha_db:/var/lib/postgresql/data

  account_db:
    build: ./dbs/account/
    container_name: account_db
    ports:
      - "127.0.0.1:5435:5432"
    env_file:
     - path: ./dbs/account/.env
    volumes:
     - account_db:/var/lib/postgresql/data

  market_db:
    build: ./dbs/market/
    container_name: market_db
    ports:
      - "127.0.0.1:5436:5432"
    env_file:
      - path: ./dbs/market/.env
    volumes:
      - market_db:/var/lib/postgresql/data

  transaction_db:
    build: ./dbs/transaction
    container_name: transaction_db
    ports:
      - "127.0.0.1:5437:5432"
    env_file:
     - path: ./dbs/transaction/.env
    volumes:
     - transaction_db:/var/lib/postgresql/data

 
  player_service:
    build: ./services/player
    container_name: player_service
    env_file:
      - path: ./services/player/.env
    ports:
      - "127.0.0.1:8080:5000"
    depends_on:
      - player_db
    links:
      - player_db
    develop:
     watch:
      - action: sync
        path: ./services/player/src
        target: /app
      - action: rebuild
        path: ./services/player/requirements.txt

  authentication_service:
    build: ./services/authentication
    container_name: authentication_service
    env_file:
      - path: ./services/authentication/.env
    ports:
      - "127.0.0.1:8081:5000"
    depends_on:
      - authentication_db
    links:
      - authentication_db
    develop:
     watch:
      - action: sync
        path: ./services/authentication/src
        target: /app
      - action: rebuild
        path: ./services/authentication/requirements.txt

  gacha_service:
    build: ./services/gacha
    container_name: gacha_service
    env_file:
      - path: ./services/gacha/.env
    ports:
      - "127.0.0.1:8082:5000"
    depends_on:
      - gacha_db
    links:
      - gacha_db
    develop:
     watch:
      - action: sync
        path: ./services/gacha/src
        target: /app
      - action: rebuild
        path: ./services/gacha/requirements.txt

  account_service:
    build: ./services/account
    container_name: account_service
    env_file:
      - path: ./services/account/.env
    ports:
      - "127.0.0.1:8083:5000"
    depends_on:
      - account_db
    links:
      - account_db
    develop:
     watch:
      - action: sync
        path: ./services/account/src
        target: /app
      - action: rebuild
        path: ./services/account/requirements.txt

  currency_service:
    build: ./services/currency
    container_name: currency_service
    ports:
      - "127.0.0.1:8084:5000"
    develop:
     watch:
      - action: sync
        path: ./services/currency/src
        target: /app
      - action: rebuild
        path: ./services/currency/requirements.txt

  market_service:
    build: ./services/market
    container_name: market_service
    env_file:
      - path: ./services/market/.env
    ports:
      - "127.0.0.1:8086:5000"
    depends_on:
      - market_db
    links:
      - market_db
    develop:
      watch:
        - action: sync
          path: ./services/market/src
          target: /app
        - action: rebuild
          path: ./services/market/requirements.txt

  transaction_service:
    build: ./services/transaction
    container_name: transaction_service
    env_file:
      - path: ./services/transaction/.env
    ports:
      - "127.0.0.1:8087:5000"
    depends_on:
      - transaction_db
    links:
      - transaction_db
    develop:
     watch:
      - action: sync
        path: ./services/transaction/src
        target: /app
      - action: rebuild
        path: ./services/transaction/requirements.txt
    
    
volumes:
 player_db:
 authentication_db:
 gacha_db:
 account_db:
 market_db:
 transaction_db:
 caddy_data:
 caddy_config:



