services:
  caddy:
    image: caddy:latest
    container_name: caddy_gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - player_service
      - authentication_service
      - gacha_service
      - account_service
      - currency_service
      - market_service
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal_net
    
  player_db:
    build: ./dbs/player
    container_name: player_db
    env_file:
      - path: ./dbs/player/.env
    volumes:
      - player_db:/var/lib/postgresql/data
    networks:
      - player_net

  admin_db:
    build: ./dbs/admin
    container_name: admin_db
    env_file:
      - path: ./dbs/admin/.env
    volumes:
      - admin_db:/var/lib/postgresql/data
    networks:
      - authentication_net

  gacha_db:
    build: ./dbs/gacha/
    container_name: gacha_db
    env_file:
      - path: ./dbs/gacha/.env
    volumes:
      - gacha_db:/var/lib/postgresql/data
    networks:
      - gacha_net

  account_db:
    build: ./dbs/account/
    container_name: account_db
    env_file:
      - path: ./dbs/account/.env
    volumes:
      - account_db:/var/lib/postgresql/data

  market_db:
    build: ./dbs/market/
    container_name: market_db
    env_file:
      - path: ./dbs/market/.env
    volumes:
      - market_db:/var/lib/postgresql/data
    networks:
      - market_net

  transaction_db:
    build: ./dbs/transaction
    container_name: transaction_db
    env_file:
      - path: ./dbs/transaction/.env
    volumes:
      - transaction_db:/var/lib/postgresql/data
    networks:
      - transaction_net

 
  player_service:
    build: ./services/player
    container_name: player_service
    env_file:
      - path: ./services/player/.env
    depends_on:
      - player_db
    networks:
      - player_net
      - internal_net
    develop:
     watch:
      - action: sync
        path: ./services/player/src
        target: /app
      - action: rebuild
        path: ./services/player/requirements.txt
        
  authentication_service:
    build: ./services/authentication
    container_name: authentication_service
    env_file:
      - path: ./services/authentication/.env
    depends_on:
      - admin_db
    networks:
      - authentication_net
      - internal_net
    develop:
     watch:
      - action: sync
        path: ./services/authentication/src
        target: /app
      - action: rebuild
        path: ./services/authentication/requirements.txt

  gacha_service:
    build: ./services/gacha
    container_name: gacha_service
    env_file:
      - path: ./services/gacha/.env
    depends_on:
      - gacha_db
    networks:
      - gacha_net
      - internal_net
    develop:
     watch:
      - action: sync
        path: ./services/gacha/src
        target: /app
      - action: rebuild
        path: ./services/gacha/requirements.txt

  account_service:
    build: ./services/account
    container_name: account_service
    env_file:
      - path: ./services/account/.env
    depends_on:
      - account_db
    networks:
      - internal_net
    develop:
     watch:
      - action: sync
        path: ./services/account/src
        target: /app
      - action: rebuild
        path: ./services/account/requirements.txt

  currency_service:
    build: ./services/currency
    container_name: currency_service
    networks:
      - internal_net
    develop:
     watch:
      - action: sync
        path: ./services/currency/src
        target: /app
      - action: rebuild
        path: ./services/currency/requirements.txt

  admin_service:
    build: ./services/admin
    container_name: admin_service
    networks:
      - internal_net
    develop:
      watch:
        - action: sync
          path: ./services/admin/src
          target: /app
        - action: rebuild
          path: ./services/admin/requirements.txt

  market_service:
    build: ./services/market
    container_name: market_service
    env_file:
      - path: ./services/market/.env
    depends_on:
      - market_db
      - rabbitmq_broker
    networks:
      - market_net
      - internal_net
    develop:
      watch:
        - action: sync
          path: ./services/market/src
          target: /app
        - action: rebuild
          path: ./services/market/requirements.txt

  transaction_service:
    build: ./services/transaction
    container_name: transaction_service
    env_file:
      - path: ./services/transaction/.env
    depends_on:
      - transaction_db
    networks:
      - transaction_net
      - internal_net
    develop:
     watch:
      - action: sync
        path: ./services/transaction/src
        target: /app
      - action: rebuild
        path: ./services/transaction/requirements.txt
    

  rabbitmq_broker:
    hostname: rabbitmq_broker
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    networks:
     - internal_net
  
  celery_worker:
    hostname: celery_worker
    build: ./services/celery
    depends_on:
     - rabbitmq_broker
    networks:
     - internal_net
    
volumes:
 player_db:
 admin_db:
 gacha_db:
 account_db:
 market_db:
 transaction_db:
 caddy_data:
 caddy_config:

networks:
 player_net:
 authentication_net:
 gacha_net:
 market_net:
 transaction_net:
 internal_net:
