services:
  player_db:
    build: ./dbs/player
    container_name: player_db
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
     - path: ./dbs/player/.env

  authentication_db:
    image: postgres:latest
    container_name: authentication_db
    ports:
      - "127.0.0.1:5433:5432"
    env_file:
      - path: ./dbs/authentication/.env

  gacha_db:
    build: ./dbs/gacha/
    container_name: gacha_db
    ports:
      - "127.0.0.1:5434:5432"
    env_file:
     - path: ./dbs/gacha/.env

 
  player_service:
    build: ./services/player
    container_name: player_service
    env_file:
      - path: ./services/player/.env
    ports:
      - "127.0.0.1:8080:5000"
    depends_on:
      - player_db
    links:
      - player_db
    volumes:
      - ./services/player/src:/app

  authentication_service:
    build: ./services/authentication
    container_name: authentication_service
    env_file:
      - path: ./services/authentication/.env
    ports:
      - "127.0.0.1:8081:5000"
    depends_on:
      - authentication_db
    links:
      - authentication_db
    volumes:
      - ./services/authentication/src:/app

  gacha_service:
    build: ./services/gacha
    container_name: gacha_service
    env_file:
      - path: ./services/gacha/.env
    ports:
      - "127.0.0.1:8082:5000"
    depends_on:
      - gacha_db
    links:
      - gacha_db
    volumes:
      - ./services/gacha/src:/app
    




