services:
  caddy_admin:
    image: caddy:2.9-alpine
    container_name: caddy_gateway_admin
    ports:
      - "127.0.0.1:8443:443"
    volumes:
      - ./Caddyfile-admin:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal_admin_net
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M

  caddy_player:
    image: caddy:2.9-alpine
    container_name: caddy_gateway_player
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - ./Caddyfile-player:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal_player_net
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M
    
  player_db:
    build: ./dbs/player
    container_name: player_db
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - path: ./dbs/player/.env
    volumes:
      - player_db:/var/lib/postgresql
    secrets:
      - player_db.crt
      - player_db.key
    networks:
      - player_net
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M

  admin_db:
    build: ./dbs/admin
    container_name: admin_db
    ports:
      - "127.0.0.1:5433:5432"
    env_file:
      - path: ./dbs/admin/.env
    volumes:
      - admin_db:/var/lib/postgresql
    secrets:
      - admin_db.crt
      - admin_db.key
    networks:
      - authentication_net
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M

  gacha_db:
    build: ./dbs/gacha/
    container_name: gacha_db
    ports:
      - "127.0.0.1:5434:5432"
    env_file:
      - path: ./dbs/gacha/.env
    volumes:
      - gacha_db:/var/lib/postgresql
    secrets:
      - gacha_db.crt
      - gacha_db.key
    networks:
      - gacha_net
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M

  market_db:
    build: ./dbs/market/
    container_name: market_db
    ports:
      - "127.0.0.1:5436:5432"
    env_file:
      - path: ./dbs/market/.env
    volumes:
      - market_db:/var/lib/postgresql
    secrets:
      - market_db.crt
      - market_db.key
    networks:
      - market_net
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3

  transaction_db:
    build: ./dbs/transaction
    container_name: transaction_db
    ports:
      - "127.0.0.1:5437:5432"
    env_file:
      - path: ./dbs/transaction/.env
    volumes:
      - transaction_db:/var/lib/postgresql
    secrets:
      - transaction_db.crt
      - transaction_db.key
    networks:
      - transaction_net
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M

 
  player_service:
    build: ./services/player
    container_name: player_service
    env_file:
      - path: ./services/player/.env
    environment:
      DEPLOYMENT_MODE: ${DEPLOYMENT_MODE:?undefined development mode}
    ports:
      - "127.0.0.1:8080:5000"
    depends_on:
      player_db:
        condition: service_healthy
    networks:
      - player_net
      - internal_player_net
      - internal_admin_net
    secrets:
      - player_certificate
      - player_key
    develop:
     watch:
      - action: rebuild
        path: ./services/player/src
        target: /app
      - action: rebuild
        path: ./services/player/requirements.txt
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 100M

  authentication_service:
    build: ./services/authentication
    container_name: authentication_service
    env_file:
      - path: ./services/authentication/.env
    environment:
      DEPLOYMENT_MODE: ${DEPLOYMENT_MODE:?undefined development mode}
    ports:
      - "127.0.0.1:8081:5000"
    depends_on:
      admin_db:
        condition: service_healthy
    networks:
      - authentication_net
      - internal_player_net
      - internal_admin_net
    secrets:
      - authentication_certificate
      - authentication_key
    develop:
     watch:
      - action: rebuild
        path: ./services/authentication/src
        target: /app
      - action: rebuild
        path: ./services/authentication/requirements.txt
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 100M

  gacha_service:
    build: ./services/gacha
    container_name: gacha_service
    env_file:
      - path: ./services/gacha/.env
    environment:
      DEPLOYMENT_MODE: ${DEPLOYMENT_MODE:?undefined development mode}
    volumes:
      - gacha_service:/app/static/images/gachas
    ports:
      - "127.0.0.1:8082:5000"
    depends_on:
        gacha_db:
          condition: service_healthy
    networks:
      - gacha_net
      - internal_player_net
      - internal_admin_net
    secrets:
      - collection_certificate
      - collection_key
    develop:
     watch:
      - action: rebuild
        path: ./services/gacha/src
        target: /app
      - action: rebuild
        path: ./services/gacha/requirements.txt

  account_service:
    build: ./services/account
    container_name: account_service
    env_file:
      - path: ./services/account/.env
    environment:
      DEPLOYMENT_MODE: ${DEPLOYMENT_MODE:?undefined development mode}
    ports:
      - "127.0.0.1:8083:5000"
    networks:
      - internal_player_net
      - internal_admin_net
    secrets:
      - account_certificate
      - account_key
    develop:
     watch:
      - action: rebuild
        path: ./services/account/src
        target: /app
      - action: rebuild
        path: ./services/account/requirements.txt
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 250M

  currency_service:
    build: ./services/currency
    container_name: currency_service
    env_file:
      - path: ./services/currency/.env
    environment:
      DEPLOYMENT_MODE: ${DEPLOYMENT_MODE:?undefined development mode}
    ports:
      - "127.0.0.1:8088:5000"
    networks:
      - internal_player_net
      - internal_admin_net
    secrets:
      - currency_certificate
      - currency_key
    develop:
     watch:
      - action: rebuild
        path: ./services/currency/src
        target: /app
      - action: rebuild
        path: ./services/currency/requirements.txt
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M

  admin_service:
    build: ./services/admin
    container_name: admin_service
    env_file:
      - path: ./services/admin/.env
    environment:
      DEPLOYMENT_MODE: ${DEPLOYMENT_MODE:?undefined development mode}
    ports:
      - "127.0.0.1:8085:5000"
    networks:
      - internal_player_net
      - internal_admin_net
    secrets:
      - admin_certificate
      - admin_key
    develop:
      watch:
        - action: rebuild
          path: ./services/admin/src
          target: /app
        - action: rebuild
          path: ./services/admin/requirements.txt
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 100M

  market_service:
    build: ./services/market
    container_name: market_service
    env_file:
      - path: ./services/market/.env
    environment:
      DEPLOYMENT_MODE: ${DEPLOYMENT_MODE:?undefined development mode}
    ports:
      - "127.0.0.1:8086:5000"
    depends_on:
      market_db:
        condition: service_healthy
      rabbitmq_broker:
        condition: service_healthy
    networks:
      - market_net
      - internal_player_net
      - internal_admin_net
    secrets:
      - market_certificate
      - market_key
      - celery_certificate
      - celery_key
    develop:
      watch:
        - action: rebuild
          path: ./services/market/src
          target: /app
        - action: rebuild
          path: ./services/market/requirements.txt
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 150M

  transaction_service:
    build: ./services/transaction
    container_name: transaction_service
    env_file:
      - path: ./services/transaction/.env
    environment:
      DEPLOYMENT_MODE: ${DEPLOYMENT_MODE:?undefined development mode}
    ports:
      - "127.0.0.1:8087:5000"
    depends_on:
      transaction_db:
        condition: service_healthy
    networks:
      - transaction_net
      - internal_player_net
      - internal_admin_net
    secrets:
      - transaction_certificate
      - transaction_key
    develop:
     watch:
      - action: rebuild
        path: ./services/transaction/src
        target: /app
      - action: rebuild
        path: ./services/transaction/requirements.txt
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 150M
    

  rabbitmq_broker:
    hostname: rabbitmq_broker
    build: ./services/rabbitmq
    container_name: rabbitmq_broker
    ports:
     - "127.0.0.1:5671:5671"
     - "127.0.0.1:15672:15672"
    networks:
     - internal_player_net
     - internal_admin_net
    secrets:
      - rabbit_certificate
      - rabbit_key
    healthcheck:
      test: curl guest:guest@127.0.0.1:15672/api/overview || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  celery_worker_1:
    hostname: celery_worker_1
    build: ./services/celery
    links:
     - rabbitmq_broker
    networks:
     - internal_player_net
     - internal_admin_net
    secrets:
      - celery_certificate
      - celery_key
    depends_on:
      rabbitmq_broker:
        condition: service_healthy
    healthcheck:
      test: celery -A mycelery inspect ping -d celery@$${HOSTNAME} || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 15s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.4'
          memory: 200M
      
  celery_worker_2:
    hostname: celery_worker_2
    build: ./services/celery
    links:
     - rabbitmq_broker
    networks:
     - internal_player_net
     - internal_admin_net
    secrets:
      - celery_certificate
      - celery_key
    depends_on:
      rabbitmq_broker:
        condition: service_healthy
    healthcheck:
      test: celery -A mycelery inspect ping -d celery@$${HOSTNAME} || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 15s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.4'
          memory: 200M
     
secrets: 
  player_db.crt:
    file: ./dbs/player/server.crt
  player_db.key:
    file: ./dbs/player/server.key
  admin_db.crt:
    file: ./dbs/admin/server.crt
  admin_db.key:
    file: ./dbs/admin/server.key
  gacha_db.crt:
    file: ./dbs/gacha/server.crt
  gacha_db.key:
    file: ./dbs/gacha/server.key
  market_db.crt:
    file: ./dbs/market/server.crt
  market_db.key:
    file: ./dbs/market/server.key
  transaction_db.crt:
    file: ./dbs/transaction/server.crt
  transaction_db.key:
    file: ./dbs/transaction/server.key
  account_certificate:
    file: ./cert/account_cert.pem
  account_key:
    file: ./cert/account_key.pem
  admin_certificate:    
    file: ./cert/admin_cert.pem
  admin_key:
    file: ./cert/admin_key.pem
  collection_certificate:
    file: ./cert/collection_cert.pem
  collection_key:
    file: ./cert/collection_key.pem
  currency_certificate:
    file: ./cert/currency_cert.pem
  currency_key:
    file: ./cert/currency_key.pem
  authentication_certificate:
    file: ./cert/authentication_cert.pem
  authentication_key: 
    file: ./cert/authentication_key.pem
  market_certificate:
    file: ./cert/market_cert.pem  
  market_key: 
    file: ./cert/market_key.pem 
  player_certificate:
    file: ./cert/player_cert.pem
  player_key: 
    file: ./cert/player_key.pem
  transaction_certificate:
    file: ./cert/transaction_cert.pem
  transaction_key:
    file: ./cert/transaction_key.pem
  celery_certificate:
    file: ./cert/celery_cert.pem
  celery_key:
    file: ./cert/celery_key.pem
  rabbit_certificate:
    file: ./cert/rabbit_cert.pem
  rabbit_key:
    file: ./cert/rabbit_key.pem

volumes:
 player_db:
 admin_db:
 gacha_db:
 market_db:
 transaction_db:
 gacha_service:
 caddy_data:
 caddy_config:

networks:
 player_net:
 authentication_net:
 gacha_net:
 market_net:
 transaction_net:
 internal_player_net:
 internal_admin_net: